import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    amount: "src/components/Amount/index.ts",
    button: "src/components/Button/index.ts",
    text: "src/components/Text/index.ts",
    divider: "src/components/Divider/index.ts",
    textfield: "src/components/TextField/index.ts",
    checkbox: "src/components/Checkbox/index.ts",
    toggle: "src/components/Toggle/index.ts",
    toast: "src/components/Toast/index.ts",
    "bottom-sheet": "src/components/BottomSheet/index.ts",
    badge: "src/components/Badge/index.ts",
    chip: "src/components/Chip/index.ts",
    card: "src/components/Card/index.ts",
    spinner: "src/components/Spinner/index.ts",
    skeleton: "src/components/Skeleton/index.ts",
    avatar: "src/components/Avatar/index.ts",
    alert: "src/components/Alert/index.ts",
    progress: "src/components/Progress/index.ts",
    textarea: "src/components/Textarea/index.ts",
    radio: "src/components/Radio/index.ts",
    empty: "src/components/Empty/index.ts",
    select: "src/components/Select/index.ts",
    tabs: "src/components/Tabs/index.ts",
    modal: "src/components/Modal/index.ts",
    tooltip: "src/components/Tooltip/index.ts",
    accordion: "src/components/Accordion/index.ts",
    slider: "src/components/Slider/index.ts",
    pagination: "src/components/Pagination/index.ts",
    stepper: "src/components/Stepper/index.ts",
    table: "src/components/Table/index.ts",
    calendar: "src/components/Calendar/index.ts",
    "date-picker": "src/components/DatePicker/index.ts",
    "otp-input": "src/components/OTPInput/index.ts",
    popover: "src/components/Popover/index.ts",
    "dropdown-menu": "src/components/DropdownMenu/index.ts",
    form: "src/components/Form/index.ts",
    icon: "src/components/Icon/index.ts",
    loading: "src/components/Loading/index.ts",
    "search-field": "src/components/SearchField/index.ts",
    "icon-button": "src/components/IconButton/index.ts",
    "segmented-control": "src/components/SegmentedControl/index.ts",
    rating: "src/components/Rating/index.ts",
    "numeric-spinner": "src/components/NumericSpinner/index.ts",
    dialog: "src/components/Dialog/index.ts",
    "bottom-cta": "src/components/BottomCTA/index.ts",
    "list-row": "src/components/ListRow/index.ts",
    result: "src/components/Result/index.ts",
    drawer: "src/components/Drawer/index.ts",
  },
  format: ["cjs", "esm"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
  treeshake: true,
});
